// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2yWKNPuGvmtDYvMuaO3e5Q0csuAx6GFY',
    appId: '1:779761398451:web:05ec4cd0f6d707995ef6c6',
    messagingSenderId: '779761398451',
    projectId: 'petcareapp-8e073',
    authDomain: 'petcareapp-8e073.firebaseapp.com',
    storageBucket: 'petcareapp-8e073.firebasestorage.app',
    measurementId: 'G-HYJBHHXV36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1aJPBDfDe0HcPdQwu8ARwphy6nmdyYA',
    appId: '1:779761398451:android:4ce03d2b854cd9965ef6c6',
    messagingSenderId: '779761398451',
    projectId: 'petcareapp-8e073',
    storageBucket: 'petcareapp-8e073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCnxrSdNJdjk8j4610-gkT1bZC0pglnWs',
    appId: '1:779761398451:ios:071b8c8786b96f655ef6c6',
    messagingSenderId: '779761398451',
    projectId: 'petcareapp-8e073',
    storageBucket: 'petcareapp-8e073.firebasestorage.app',
    iosBundleId: 'com.example.petCareShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCnxrSdNJdjk8j4610-gkT1bZC0pglnWs',
    appId: '1:779761398451:ios:071b8c8786b96f655ef6c6',
    messagingSenderId: '779761398451',
    projectId: 'petcareapp-8e073',
    storageBucket: 'petcareapp-8e073.firebasestorage.app',
    iosBundleId: 'com.example.petCareShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2yWKNPuGvmtDYvMuaO3e5Q0csuAx6GFY',
    appId: '1:779761398451:web:8c94c8bce7466b6a5ef6c6',
    messagingSenderId: '779761398451',
    projectId: 'petcareapp-8e073',
    authDomain: 'petcareapp-8e073.firebaseapp.com',
    storageBucket: 'petcareapp-8e073.firebasestorage.app',
    measurementId: 'G-GP8RNYNGP8',
  );
}
